FROM yi/tflow-gui:latest
 
MAINTAINER Igor Rabkin <igor.rabkin@xiaoyi.com>


##################################################################
#                     Possible TensorRT Support                  #
##################################################################

 RUN apt-get update && \
        apt-get install nvinfer-runtime-trt-repo-ubuntu1604-5.0.2-ga-cuda10.0 \
        && apt-get update \
        && apt-get install -y --no-install-recommends \
	   libnvinfer5=5.0.2-1+cuda10.0 \
	   libnvinfer-dev=5.0.2-1+cuda10.0 && \
           rm -rf /var/lib/apt/lists/*
	

################################################################## 
#              Pick up some TF dependencies                      #
##################################################################

RUN apt-get update && apt-get install -y --no-install-recommends \ 		 
    libfreetype6-dev \
    libpng12-dev \ 
    libzmq3-dev \
    libcurl3-dev \
    libgoogle-perftools-dev \
    zlib1g-dev \
    pkg-config \ 
    python \ 
    python-dev \
    python-tk && \    
    apt-get clean && \ 
    rm -rf /var/lib/apt/lists/* 
    
    
################################	
# Updating PIP and Dependences #
################################

RUN curl -fSsL -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py
    
   
RUN python -m pip --no-cache-dir install \ 
    networkx \
    pytest \
    ipykernel \
    numpy \
    pandas \
    scipy \
    sklearn \
    scikit-learn \
    tqdm \
    click==6.7 \
    more_itertools \
    utils \
    bs4 \
    opencv-python \
    python-utils \
    scikit-image \
    xmltodict \
    easydict \
    sacred \
    tables \
    glances \
    gpustat \
    texttable \
    albumentations \
    urllib3==1.21.1 && \
    python -m ipykernel.kernelspec && \
    apt-get clean && \ 
    rm -rf /var/lib/apt/lists/*
    

#################################################
#     Install HDF5 with multithread support     #
#################################################

RUN curl -OSL https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.20/src/hdf5-1.8.20.tar && \
    tar -xvf hdf5-1.8.20.tar && \
    cd hdf5-1.8.20 && \
    ./configure --enable-threadsafe  --enable-unsupported --prefix /usr/local && \
    make -j "$(nproc)" && \
    make install && \
    cd .. && \
    rm hdf5-1.8.20.tar && rm -rf hdf5-1.8.20.tar && \
    apt-get clean && \ 
    rm -rf /var/lib/apt/lists/*
    
    ENV HDF5_DIR=/usr/local 
    RUN python -m pip --no-cache-dir install --no-binary=h5py h5py
    
    
##########################################
#       Install PyTorch & Dependences    #
##########################################

  RUN apt-get update && apt-get install -y --no-install-recommends \
      libgraphviz-dev 
        
  RUN python -m pip --no-cache-dir install \
      ipdb \
      imageio \
      graphviz \
      tensorboardX \
      qpth==0.0.13 \
      torchnet && \
      apt-get clean && \ 
      rm -rf /var/lib/apt/lists/*
	  
  RUN git clone https://github.com/pygraphviz/pygraphviz.git && \
      cd pygraphviz && \
      python setup.py install --include-path=/usr/include/graphviz --library-path=/usr/lib/graphviz/ && \
      rm -rf pygraphviz && \
      apt-get clean && \ 
      rm -rf /var/lib/apt/lists/*	  
	  
  RUN python -m pip --no-cache-dir install \
      torch==1.0.1.post2 \
      torchvision==0.2.2.post2 && \
      apt-get clean && \ 
      rm -rf /var/lib/apt/lists/*
      
       
##################################################
# Configure the build for our CUDA configuration #
##################################################

ENV CI_BUILD_PYTHON python
ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH
ENV TF_NEED_CUDA 1
ENV TF_CUDA_COMPUTE_CAPABILITIES=7.0
ENV TF_CUDA_VERSION=10.0
ENV TF_CUDNN_VERSION=7
ENV TF_NCCL_VERSION=2.4
ENV TF_NEED_TENSORRT 0


################ INTEL MKL SUPPORT #################

ENV LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH
ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
RUN cd /usr/local/lib && \
    curl -OSL ftp://jenkins-cloud/pub/LIB/libiomp5.so -o libiomp5.so && \
    curl -OSL ftp://jenkins-cloud/pub/LIB/libmklml_gnu.so -o libmklml_gnu.so && \
    curl -OSL ftp://jenkins-cloud/pub/LIB/libmklml_intel.so -o libmklml_intel.so
    
####################################################
