FROM yi/tflow-gui:latest
 
MAINTAINER Igor Rabkin <igor.rabkin@xiaoyi.com>


##################################################################
#                Pick up some TF dependencies                    #
##################################################################

RUN apt-get update && apt-get install -y --no-install-recommends \ 
         libfreetype6-dev \
         libpng12-dev \ 
         libzmq3-dev \
         libcurl3-dev \
         libgoogle-perftools-dev \		 
         pkg-config \ 
         python \ 
         python-dev 
          
#################################################
#     Python installations for dev              #
#################################################
	
RUN apt-get install -y --no-install-recommends \
    python-opencv \
    python-bs4 \
    python-tk \
    python-pandas \
    python-sklearn \
    python-urllib3 \
    python-xmltodict \
    python-elasticsearch \
    python-skimage-lib && \
    apt-get clean && \ 
    rm -rf /var/lib/apt/lists/*

	
################################	
# Updating PIP and Dependences #
################################

RUN curl -fSsL -O https://bootstrap.pypa.io/get-pip.py && \
    python get-pip.py && \
    rm get-pip.py	
 
RUN pip --no-cache-dir install \ 
        Pillow \
	toposort \
	networkx \
	pytest \
    h5py \
    ipykernel \
    jupyter \
    matplotlib \
    numpy==1.14.5 \
    pandas \
    scipy \
     sklearn \
	tensorlayer \
	scikit-learn \
	tqdm \
	tflearn \
	more_itertools \
	pymongo \
	sacred \
        && \
    python -m ipykernel.kernelspec 
	
###################################
# Install TensorFlow GPU version. #
###################################

RUN cd /
ARG CRED="server:123server123"
ARG FTP_PATH
ARG FILE_NAME
RUN curl -u ${CRED} ${FTP_PATH} -o ${FILE_NAME} && \
    pip --no-cache-dir install --upgrade ${FILE_NAME} && \
    rm -f ${FILE_NAME}
    
  
##################################################
# Configure the build for our CUDA configuration #
##################################################

ENV CI_BUILD_PYTHON python
ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH
ENV TF_NEED_CUDA 1
ENV TF_CUDA_COMPUTE_CAPABILITIES=5.2,6.1
ENV TF_CUDA_VERSION=9.0
ENV TF_CUDNN_VERSION=7.0
 
################ INTEL MKL SUPPORT #################

ENV LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH
ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
RUN cd /usr/local/lib && \
    curl -u ${CRED} ftp://yifileserver/IT/YiIT/lib/libiomp5.so -o libiomp5.so && \
    curl -u ${CRED} ftp://yifileserver/IT/YiIT/lib/libmklml_gnu.so -o libmklml_gnu.so && \
    curl -u ${CRED} ftp://yifileserver/IT/YiIT/lib/libmklml_intel.so -o libmklml_intel.so
    
####################################################
